### ISSUE TITLE
Vínculo com Usuário

### ISSUE THREAD

**Issue by mayronceccon** [lucasmarques73/web-complaints#1]
@lucasmarques73 senti falta de um vínculo com usuário, para saber qual é o status de suas reclamações.

**Comment by lucasmarques73** [comment]
Sobre essa parte, a ideia é de que seja uma denúncia anônima então eu não teria nenhuma informação de quem fez a denúncia, mas você me deu uma ideia boa. Posso colocar um botão para quem quiser acompanhar a denúncia e não somente quem fez ela. Tipo o botão Watch aqui do github. Obrigado pela dica.

**Comment by lucasmarques73** [comment]
Adicionei uma tabela de Followers para quem quiser acompanhar a denúncia.
