### ISSUE TITLE
Local da organização

### ISSUE THREAD

**Issue by mayronceccon** [lucasmarques73/web-complaints#2]
Poderia ter a opção de selecionar cidade/estado para as organizações.

**Comment by lucasmarques73** [comment]
Eu tinha pensado nisso e esqueci de colocar.. Vou criar uma tabela de Address e relacionar com Organization pois um Orgão pode ter mais de um endereço.

**Comment by lucasmarques73** [comment]
Adicionei a tabela de address para termos os endereços das organizações
